; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4d_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4d_app_2:
	DB	"Starting kernel...",0xA,0
L_lab4d_app_1:
	DB	"Creating tasks...",0xA,0
	ALIGN	2
main:
	jmp	L_lab4d_app_3
L_lab4d_app_4:
	call	YKInitialize
	mov	ax, L_lab4d_app_1
	push	ax
	call	printString
	add	sp, 2
	mov	al, 3
	push	ax
	mov	ax, (AStk+512)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	al, 5
	push	ax
	mov	ax, (BStk+512)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	al, 7
	push	ax
	mov	ax, (CStk+512)
	push	ax
	mov	ax, CTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	al, 8
	push	ax
	mov	ax, (DStk+512)
	push	ax
	mov	ax, DTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	ax, L_lab4d_app_2
	push	ax
	call	printString
	add	sp, 2
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4d_app_3:
	push	bp
	mov	bp, sp
	jmp	L_lab4d_app_4
L_lab4d_app_7:
	DB	"Task A, delaying 2.",0xA,0
L_lab4d_app_6:
	DB	"Task A started.",0xA,0
	ALIGN	2
ATask:
	jmp	L_lab4d_app_8
L_lab4d_app_9:
	mov	ax, L_lab4d_app_6
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab4d_app_11
L_lab4d_app_10:
	mov	ax, L_lab4d_app_7
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4d_app_11:
	jmp	L_lab4d_app_10
L_lab4d_app_12:
	mov	sp, bp
	pop	bp
	ret
L_lab4d_app_8:
	push	bp
	mov	bp, sp
	jmp	L_lab4d_app_9
L_lab4d_app_15:
	DB	"Task B, delaying 3.",0xA,0
L_lab4d_app_14:
	DB	"Task B started.",0xA,0
	ALIGN	2
BTask:
	jmp	L_lab4d_app_16
L_lab4d_app_17:
	mov	ax, L_lab4d_app_14
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab4d_app_19
L_lab4d_app_18:
	mov	ax, L_lab4d_app_15
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 3
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4d_app_19:
	jmp	L_lab4d_app_18
L_lab4d_app_20:
	mov	sp, bp
	pop	bp
	ret
L_lab4d_app_16:
	push	bp
	mov	bp, sp
	jmp	L_lab4d_app_17
L_lab4d_app_23:
	DB	"Task C, delaying 5.",0xA,0
L_lab4d_app_22:
	DB	"Task C started.",0xA,0
	ALIGN	2
CTask:
	jmp	L_lab4d_app_24
L_lab4d_app_25:
	mov	ax, L_lab4d_app_22
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab4d_app_27
L_lab4d_app_26:
	mov	ax, L_lab4d_app_23
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4d_app_27:
	jmp	L_lab4d_app_26
L_lab4d_app_28:
	mov	sp, bp
	pop	bp
	ret
L_lab4d_app_24:
	push	bp
	mov	bp, sp
	jmp	L_lab4d_app_25
L_lab4d_app_31:
	DB	"Task D, delaying 10.",0xA,0
L_lab4d_app_30:
	DB	"Task D started.",0xA,0
	ALIGN	2
DTask:
	jmp	L_lab4d_app_32
L_lab4d_app_33:
	mov	ax, L_lab4d_app_30
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab4d_app_35
L_lab4d_app_34:
	mov	ax, L_lab4d_app_31
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 10
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4d_app_35:
	jmp	L_lab4d_app_34
L_lab4d_app_36:
	mov	sp, bp
	pop	bp
	ret
L_lab4d_app_32:
	push	bp
	mov	bp, sp
	jmp	L_lab4d_app_33
	ALIGN	2
AStk:
	TIMES	512 db 0
BStk:
	TIMES	512 db 0
CStk:
	TIMES	512 db 0
DStk:
	TIMES	512 db 0
