; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4c_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4c_app_2:
	DB	"Starting kernel...",0xA,0
L_lab4c_app_1:
	DB	"Creating task...",0xA,0
	ALIGN	2
main:
	jmp	L_lab4c_app_3
L_lab4c_app_4:
	call	YKInitialize
	mov	ax, L_lab4c_app_1
	push	ax
	call	printString
	add	sp, 2
	xor	al, al
	push	ax
	mov	ax, (TaskStack+512)
	push	ax
	mov	ax, Task
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	ax, L_lab4c_app_2
	push	ax
	call	printString
	add	sp, 2
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4c_app_3:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_app_4
L_lab4c_app_9:
	DB	" context switches! YKIdleCount is ",0
L_lab4c_app_8:
	DB	"Task running after ",0
L_lab4c_app_7:
	DB	"Delaying task...",0xA,0
L_lab4c_app_6:
	DB	"Task started.",0xA,0
	ALIGN	2
Task:
	jmp	L_lab4c_app_10
L_lab4c_app_11:
	mov	ax, L_lab4c_app_6
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab4c_app_13
L_lab4c_app_12:
	mov	ax, L_lab4c_app_7
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	call	YKEnterMutex
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	mov	ax, word [YKIdleCount]
	mov	word [bp-2], ax
	mov	word [YKIdleCount], 0
	call	YKExitMutex
	mov	ax, L_lab4c_app_8
	push	ax
	call	printString
	add	sp, 2
	push	word [bp-4]
	call	printUInt
	add	sp, 2
	mov	ax, L_lab4c_app_9
	push	ax
	call	printString
	add	sp, 2
	push	word [bp-2]
	call	printUInt
	add	sp, 2
	mov	ax, (L_lab4c_app_1+15)
	push	ax
	call	printString
	add	sp, 2
L_lab4c_app_13:
	jmp	L_lab4c_app_12
L_lab4c_app_14:
	mov	sp, bp
	pop	bp
	ret
L_lab4c_app_10:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_lab4c_app_11
	ALIGN	2
TaskStack:
	TIMES	512 db 0
