; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
started_running:
	DB	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	29
	; >>>>> void YKInitialize(void){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	33
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	34
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	35
	; >>>>> YKCurrentlyExecuting = 0; 
	mov	word [YKCurrentlyExecuting], 0
	; >>>>> Line:	42
	; >>>>> YKAvailTCBList = &(YKTCBArray[0]); 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	43
	; >>>>> for (i = 0; i < 3; i++) 
	mov	word [bp-2], 0
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	44
	; >>>>> YKTCBArray[i].next = &(YKTCBArray[i+1]); 
	mov	ax, word [bp-2]
	inc	ax
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	push	ax
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	mov	dx, ax
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 10
	pop	ax
	mov	word [si], ax
L_yakc_6:
	inc	word [bp-2]
L_yakc_4:
	cmp	word [bp-2], 3
	jl	L_yakc_3
L_yakc_5:
	; >>>>> Line:	45
	; >>>>> YKTCBArray[3].next = 0; 
	mov	word [(52+YKTCBArray)], 0
	; >>>>> Line:	56
	; >>>>> YKNewTask(YKIdleTask, 
	mov	al, 100
	push	ax
	mov	ax, (idleStack+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	60
	; >>>>> void YKIdleTask(void) { 
	jmp	L_yakc_8
L_yakc_9:
	; >>>>> Line:	62
	; >>>>> while(1){ 
	jmp	L_yakc_11
L_yakc_10:
	; >>>>> Line:	64
	; >>>>> YKIdleCount++; 
	inc	word [YKIdleCount]
L_yakc_11:
	jmp	L_yakc_10
L_yakc_12:
	mov	sp, bp
	pop	bp
	ret
L_yakc_8:
	push	bp
	mov	bp, sp
	jmp	L_yakc_9
	ALIGN	2
YKNewTask:
	; >>>>> Line:	76
	; >>>>> void YKNewTask(void (*task)(void), void *taskStack, unsigned char priority){ 
	jmp	L_yakc_14
L_yakc_15:
	; >>>>> Line:	87
	; >>>>> tmp = YKAvailTCBList; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	88
	; >>>>> YKAvailTCBList = tmp->next; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	; >>>>> Line:	92
	; >>>>> tmp->delay = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	98
	; >>>>> tmp->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], ax
	; >>>>> Line:	105
	; >>>>> if (YKRdyList == 0) { 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_16
	; >>>>> Line:	106
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	; >>>>> Line:	107
	; >>>>> tmp->next = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	108
	; >>>>> tmp->prev = 0; 
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	jmp	L_yakc_17
L_yakc_16:
	; >>>>> Line:	110
	; >>>>> tmp2 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	111
	; >>>>> while (tmp2->priority < tmp->priority) 
	jmp	L_yakc_19
L_yakc_18:
	; >>>>> Line:	112
	; >>>>> tmp2 = tmp2->next; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_19:
	mov	si, word [bp-4]
	add	si, 6
	mov	di, word [bp-2]
	add	di, 6
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_18
L_yakc_20:
	; >>>>> Line:	113
	; >>>>> if (tmp2->prev = 
	mov	si, word [bp-4]
	add	si, 12
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_21
	; >>>>> Line:	114
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_22
L_yakc_21:
	; >>>>> Line:	116
	; >>>>> tmp2->prev->next = tmp; 
	mov	si, word [bp-4]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_22:
	; >>>>> Line:	117
	; >>>>> tmp->prev = tmp2->prev; 
	mov	si, word [bp-4]
	add	si, 12
	mov	di, word [bp-2]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	118
	; >>>>> tmp->next = tmp2; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	119
	; >>>>> tmp2->prev = tmp; 
	mov	si, word [bp-4]
	add	si, 12
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_17:
	; >>>>> Line:	130
	; >>>>> tmp->stackptr = taskStack; 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	131
	; >>>>> tmp->ss = 0; 
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	134
	; >>>>> tmp->stackptr = tmp->stackptr - 11; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, 22
	mov	word [si], ax
	; >>>>> Line:	135
	; >>>>> *(tmp->stackptr+11) = 0x200; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 22
	mov	word [si], 512
	; >>>>> Line:	136
	; >>>>> *(tmp->stackptr+10) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	137
	; >>>>> *(tmp->stackptr+9) = (int)task; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 18
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	138
	; >>>>> *(tmp->stackptr+8) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	139
	; >>>>> *(tmp->stackptr+7) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 14
	mov	word [si], 0
	; >>>>> Line:	140
	; >>>>> *(tmp->stackptr+6) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	141
	; >>>>> *(tmp->stackptr+5) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	142
	; >>>>> *(tmp->stackptr+4) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	143
	; >>>>> *(tmp->stackptr+3) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	144
	; >>>>> *(tmp->stackptr+2) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	145
	; >>>>> *(tmp->stackptr+1) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	146
	; >>>>> *(tmp->stackptr+0) = 0; 
	mov	si, word [bp-2]
	mov	si, word [si]
	mov	word [si], 0
	; >>>>> Line:	151
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_14:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_15
	ALIGN	2
YKRun:
	; >>>>> Line:	158
	; >>>>> void YKRun(void) { 
	jmp	L_yakc_24
L_yakc_25:
	; >>>>> Line:	160
	; >>>>> started_running = 1; 
	mov	byte [started_running], 1
	; >>>>> Line:	161
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_24:
	push	bp
	mov	bp, sp
	jmp	L_yakc_25
L_yakc_29:
	DB	" which has stack ",0
L_yakc_28:
	DB	"scheduler here. dispatcher will load ",0
L_yakc_27:
	DB	"THIS SHOULD NEVER HAPPEN",0xA,"THIS SHOULD NEVER HAPPEN",0xA,0
	ALIGN	2
YKScheduler_old:
	; >>>>> Line:	170
	; >>>>> void YKScheduler_old(void) { 
	jmp	L_yakc_30
L_yakc_31:
	; >>>>> Line:	174
	; >>>>> printString("THIS SHOULD NEVER HAPPEN\nTHIS SHOULD NEVER HAPPEN\n"); 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	174
	; >>>>> printString("THIS SHOULD NEVER HAPPEN\nTHIS SHOULD NEVER HAPPEN\n"); 
	mov	ax, L_yakc_27
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	175
	; >>>>> printString("scheduler here. dispatcher will load "); 
	mov	ax, L_yakc_28
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	176
	; >>>>> printInt((int)highest_priority_task); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	177
	; >>>>> printString(" which has stack "); 
	mov	ax, L_yakc_29
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	178
	; >>>>> printInt((int)highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	179
	; >>>>> printString("\n"); 
	mov	ax, (L_yakc_27+49)
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	199
	; >>>>> if(started_running){ 
	mov	al, byte [started_running]
	test	al, al
	je	L_yakc_32
	; >>>>> Line:	200
	; >>>>> if(YKCurr 
	mov	ax, word [bp-2]
	cmp	ax, word [YKCurrentlyExecuting]
	jne	L_yakc_33
	; >>>>> Line:	201
	; >>>>> return; 
	jmp	L_yakc_34
L_yakc_33:
	; >>>>> Line:	204
	; >>>>> YKCtxSwCount = YKCtxSwCount + 1; 
	mov	ax, word [YKCtxSwCount]
	inc	ax
	mov	word [YKCtxSwCount], ax
	; >>>>> Line:	205
	; >>>>> YKCurrentlyExecuting = highest_priority_task; 
	mov	ax, word [bp-2]
	mov	word [YKCurrentlyExecuting], ax
	; >>>>> Line:	207
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_32:
L_yakc_34:
	mov	sp, bp
	pop	bp
	ret
L_yakc_30:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_31
L_yakc_43:
	DB	"scheduler called, need to save context",0xA,0
L_yakc_42:
	DB	"highest_priority_task ",0
L_yakc_41:
	DB	" and SS ",0
L_yakc_40:
	DB	"giving the dispatcher stackptr",0
L_yakc_39:
	DB	"scheduler called, no need to save context",0xA,0
L_yakc_38:
	DB	"scheduler called; returning to task",0xA,0
L_yakc_37:
	DB	"scheduler called, but not yet running",0xA,0
L_yakc_36:
	DB	"YKRdyList: ",0
	ALIGN	2
YKScheduler:
	; >>>>> Line:	211
	; >>>>> void YKScheduler(int need_to_save_context){ 
	jmp	L_yakc_44
L_yakc_45:
	; >>>>> Line:	215
	; >>>>> printString("YKRdyList: "); 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	mov	ax, word [YKCurrentlyExecuting]
	mov	word [bp-4], ax
	; >>>>> Line:	215
	; >>>>> printString("YKRdyList: "); 
	mov	ax, L_yakc_36
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	216
	; >>>>> printInt((int)YKRdyList); 
	push	word [YKRdyList]
	call	printInt
	add	sp, 2
	; >>>>> Line:	217
	; >>>>> printString("\n"); 
	mov	ax, (L_yakc_27+49)
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	220
	; >>>>> if(!started_running){ 
	mov	al, byte [started_running]
	test	al, al
	jne	L_yakc_46
	; >>>>> Line:	221
	; >>>>> printString("scheduler called, but not yet running\n"); 
	mov	ax, L_yakc_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	222
	; >>>>> return; 
	jmp	L_yakc_47
L_yakc_46:
	; >>>>> Line:	224
	; >>>>> if(YKCurrentlyExecuting == highest 
	mov	ax, word [bp-2]
	cmp	ax, word [YKCurrentlyExecuting]
	jne	L_yakc_48
	; >>>>> Line:	225
	; >>>>> printString("scheduler called; returning to task\n"); 
	mov	ax, L_yakc_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	226
	; >>>>> return; 
	jmp	L_yakc_47
L_yakc_48:
	; >>>>> Line:	229
	; >>>>> YKCtxSwCount = YKCtxSwCount + 1; 
	mov	ax, word [YKCtxSwCount]
	inc	ax
	mov	word [YKCtxSwCount], ax
	; >>>>> Line:	230
	; >>>>> YKCurrentlyExecuting = highest_priority_task; 
	mov	ax, word [bp-2]
	mov	word [YKCurrentlyExecuting], ax
	; >>>>> Line:	233
	; >>>>> if(!need_to_save_context){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_49
	; >>>>> Line:	234
	; >>>>> printString("scheduler called, no need to save context\n"); 
	mov	ax, L_yakc_39
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	235
	; >>>>> printString("giving the dispatcher stackptr"); 
	mov	ax, L_yakc_40
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	236
	; >>>>> printInt((int)highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	237
	; >>>>> printString(" and SS "); 
	mov	ax, L_yakc_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	238
	; >>>>> printInt((int)highest_priority_task->ss); 
	mov	si, word [bp-2]
	add	si, 2
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	239
	; >>>>> printString("highest_priority_task "); 
	mov	ax, L_yakc_42
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	240
	; >>>>> printInt((int)highest_priority_task); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	241
	; >>>>>  
	mov	ax, (L_yakc_27+49)
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	242
	; >>>>> YKDispatcher_save_context(0,(int *) 1, (int *)1, 
	mov	si, word [bp-2]
	add	si, 2
	push	word [si]
	mov	si, word [bp-2]
	push	word [si]
	mov	ax, 1
	push	ax
	mov	ax, 1
	push	ax
	xor	ax, ax
	push	ax
	call	YKDispatcher_save_context
	add	sp, 10
	jmp	L_yakc_50
L_yakc_49:
	; >>>>> Line:	248
	; >>>>> printString("scheduler called, need to save context\n"); 
	mov	ax, L_yakc_43
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	249
	; >>>>> YKDispatcher_save_context(need_to_save_context, 
	mov	si, word [bp-2]
	add	si, 2
	push	word [si]
	mov	si, word [bp-2]
	push	word [si]
	mov	si, word [bp-4]
	add	si, 2
	push	word [si]
	mov	si, word [bp-4]
	push	word [si]
	push	word [bp+4]
	call	YKDispatcher_save_context
	add	sp, 10
L_yakc_50:
L_yakc_47:
	mov	sp, bp
	pop	bp
	ret
L_yakc_44:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_45
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	268
	; >>>>> { 
	jmp	L_yakc_52
L_yakc_53:
	; >>>>> Line:	271
	; >>>>> if(count != 0) 
	mov	ax, word [bp+4]
	test	ax, ax
	je	L_yakc_54
L_yakc_54:
	; >>>>> Line:	278
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_52:
	push	bp
	mov	bp, sp
	jmp	L_yakc_53
L_yakc_56:
	DB	"called YKTickHandler() currently within it",0xA,0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	296
	; >>>>> { 
	jmp	L_yakc_57
L_yakc_58:
	; >>>>> Line:	297
	; >>>>> printString("called YKTickHandler() currently within it\n"); 
	mov	ax, L_yakc_56
	push	ax
	call	printString
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_57:
	push	bp
	mov	bp, sp
	jmp	L_yakc_58
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKSuspList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	56 db 0
idleStack:
	TIMES	512 db 0
YKCurrentlyExecuting:
	TIMES	2 db 0
